version: "3"

includes:
  deps:
    taskfile: taskfiles/deps.yaml
    flatten: true
  build:
    taskfile: taskfiles/build.yaml
    flatten: true
  release:
    taskfile: taskfiles/release.yaml
    flatten: true
  tests:
    taskfile: taskfiles/tests.yaml
    flatten: true
  review:
    taskfile: taskfiles/review.yaml
    flatten: true

tasks:
  default:
    - task --list-all
