version: '3'

tasks:
    build:
        desc: "Cargo debug build"
        cmds:
            - time cargo build

    build-without-warnings:
        desc: "Cargo debug build"
        env:
          RUSTFLAGS: -Awarnings
        cmds:
            - task: build
